[tool.poetry]
name = "dummy-remote"
version = "0.1.0"
description = ""
authors = ["Sahil Dilwali <sahil.dilwali@bp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
